FROM golang:1.14-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

COPY .env .

EXPOSE 5000
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o web main.go

FROM scratch
COPY --from=builder /app/web /web
COPY --from=builder /app/.env /.env
COPY --from=builder /app/views /views

CMD ["./web"]
